version: "3.8"

services:
  database:
    container_name: Database
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_USER: dev
      MYSQL_PASSWORD: developer
      MYSQL_DATABASE: pizzabrei
    ports:
      - "3306:3306"